#!/bin/sh
#
# Gradle start up script for POSIX generated by "Gradle init"
JAVA_OPTS="$JAVA_OPTS"
APP_HOME="`pwd -P`"
APP_BASE_NAME=`basename "$0"`
APP_HOME="$APP_HOME"
CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar
# Find java
if [ -n "$JAVA_HOME" ] ; then
    JAVACMD="$JAVA_HOME/bin/java"
else
    JAVACMD="java"
fi
exec "$JAVACMD" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS \
  "-Dorg.gradle.appname=$APP_BASE_NAME" \
  -classpath "$CLASSPATH" \
  org.gradle.wrapper.GradleWrapperMain "$@"
